accounts/urls.py
from django.urls import path

from accounts.views import login_view, logout_view, register_view, update_view, delete_view, contact_view

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('update/', update_view, name='update'),
    path('delete/', delete_view, name='delete'),
    path('contact/', contact_view, name='contact'),
]

scraping/urls.py
from django.urls import path

from scraping.views import home_view, list_view, detail_view, DetailPageView, ListPageView, CreatePageView, \
    UpdatePageView, DeletePageView

app_name = 'scraping'

urlpatterns = [
    # path('detail/<int:pk>/', detail_view, name='detail'),
    # path('list/', list_view, name='list'),
    path('detail/<int:pk>/', DetailPageView.as_view(), name='detail'),
    path('create/', CreatePageView.as_view(), name='create'),
    path('update/<int:pk>/', UpdatePageView.as_view(), name='update'),
    path('delete/<int:pk>/', DeletePageView.as_view(), name='delete'),
    path('list/', ListPageView.as_view(), name='list'),
    path('', home_view, name='home'),
]

scraping_service/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scraping.urls', namespace='scraping')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

scraping/models.py
from django.db import models
from django.utils.text import slugify as django_slugify
from transliterate import slugify


class City(models.Model):
    name = models.CharField(max_length=50, unique=True, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=50, blank=True, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(str(self.name))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'
        ordering = ['name']


class Language(models.Model):
    name = models.CharField(max_length=50, unique=True, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=50, blank=True, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = django_slugify(str(self.name))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Язык програмиирования'
        verbose_name_plural = 'Языки программирования'
        ordering = ['name']


class Vacancy(models.Model):
    url = models.URLField(unique=True, db_index=True, verbose_name='URL')
    title = models.CharField(max_length=250, verbose_name='Название вакансии')
    company = models.CharField(max_length=250, verbose_name='Компания')
    description = models.TextField(verbose_name='Описание вакансии')
    city = models.ForeignKey(City, on_delete=models.PROTECT, related_name='vacancies_city', verbose_name='Город')
    language = models.ForeignKey(Language, on_delete=models.PROTECT, related_name='vacancies_lang',
                                 verbose_name='Язык программирования')
    timestamp = models.DateField(auto_now_add=True, verbose_name='Дата')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'
        ordering = ['-timestamp']


class Error(models.Model):
    timestamp = models.DateField(auto_now_add=True, verbose_name='Дата')
    data = models.JSONField(verbose_name='Данные ошибки')

    def __str__(self):
        return f'Ошибка {self.pk} на {str(self.timestamp)}'

    class Meta:
        verbose_name = 'Ошибка'
        verbose_name_plural = 'Ошибки'
        ordering = ['-timestamp']


def default_urls():
    return {'superjob': '', 'headhunter': '', 'rabota': ''}


class Url(models.Model):
    city = models.ForeignKey(City, on_delete=models.PROTECT, related_name='urls_city', verbose_name='Город')
    language = models.ForeignKey(Language, on_delete=models.PROTECT, related_name='urls_lang',
                                 verbose_name='Язык программирования')
    url_data = models.JSONField(default=default_urls, verbose_name='Данные URL')

    def __str__(self):
        return f'Url {self.city} - {self.language}'

    class Meta:
        verbose_name = 'URL'
        verbose_name_plural = 'URLs'
        unique_together = ('city', 'language')

scraping/forms.py
from django import forms

from scraping.models import City, Language, Vacancy


class SearchForm(forms.Form):
    city = forms.ModelChoiceField(queryset=City.objects.all(), to_field_name='slug', required=False, label='Город',
                                  widget=forms.Select(attrs={'class': 'form-control'}))
    language = forms.ModelChoiceField(queryset=Language.objects.all(), to_field_name='slug', required=False,
                                      label='Язык программирования',
                                      widget=forms.Select(attrs={'class': 'form-control'}))


class CreateForm(forms.ModelForm):
    url = forms.CharField(label='URL', widget=forms.URLInput(attrs={'class': 'form-control'}))
    title = forms.CharField(label='Название вакансии', widget=forms.TextInput(attrs={'class': 'form-control'}))
    company = forms.CharField(label='Компания', widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(label='Описание вакансии', widget=forms.Textarea(attrs={'class': 'form-control'}))
    city = forms.ModelChoiceField(queryset=City.objects.all(), label='Город',
                                  widget=forms.Select(attrs={'class': 'form-control'}))
    language = forms.ModelChoiceField(queryset=Language.objects.all(), label='Язык программирования',
                                      widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Vacancy
        fields = '__all__'

scraping/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from scraping.forms import SearchForm, CreateForm
from scraping.models import Vacancy


def home_view(request):
    form = SearchForm()

    context = {'form': form}
    return render(request, 'scraping/index.html', context=context)


def list_view(request):
    form = SearchForm()
    city = request.GET.get('city')
    language = request.GET.get('language')
    page_vacancies = []

    if city or language:
        filtered = {}
        if city:
            filtered['city__slug'] = city
        if language:
            filtered['language__slug'] = language
        vacancies_list = Vacancy.objects.filter(**filtered).select_related('city', 'language')

        paginator = Paginator(vacancies_list, 10)
        page_number = request.GET.get('page')
        page_vacancies = paginator.get_page(page_number)

    context = {
        'vacancies': page_vacancies,
        'form': form,
        'city': city,
        'language': language,
    }
    return render(request, 'scraping/list.html', context=context)


def detail_view(request, pk):
    # obj = Vacancy.objects.get(pk=pk)
    obj = get_object_or_404(Vacancy, pk=pk)
    return render(request, 'scraping/detail.html', {'object': obj})


class DetailPageView(DetailView):
    queryset = Vacancy.objects.all()
    template_name = 'scraping/detail.html'


class ListPageView(ListView):
    model = Vacancy
    template_name = 'scraping/list.html'
    form = SearchForm()
    context_object_name = 'vacancies'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['city'] = self.request.GET.get('city')
        context['language'] = self.request.GET.get('language')
        context['form'] = self.form
        context['vacancies'] = context['page_obj']
        return context

    def get_queryset(self):
        city = self.request.GET.get('city')
        language = self.request.GET.get('language')
        page_vacancies = []
        if city or language:
            filtered = {}
            if city:
                filtered['city__slug'] = city
            if language:
                filtered['language__slug'] = language
            page_vacancies = Vacancy.objects.filter(**filtered).select_related('city', 'language')
        return page_vacancies


class CreatePageView(CreateView):
    model = Vacancy
    template_name = 'scraping/create.html'
    form_class = CreateForm
    success_url = reverse_lazy('scraping:home')


class UpdatePageView(UpdateView):
    model = Vacancy
    template_name = 'scraping/create.html'
    form_class = CreateForm
    success_url = reverse_lazy('scraping:home')


class DeletePageView(SuccessMessageMixin, DeleteView):
    model = Vacancy
    template_name = 'scraping/delete.html'
    success_url = reverse_lazy('scraping:home')
    success_message = 'Данные успешно удалены.'

scraping/templates/scraping/create.html
{% extends 'base.html' %}

{% block title %}Вакансия :: {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card mt-3">
          <h5 class="card-header">Создание вакансии</h5>
          <div class="card-body">
            <form action="{% url 'scraping:create' %}" method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

scraping/templates/scraping/delete.html
{% extends 'base.html' %}

{% block title %}Удаление вакансии :: {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div>
        <div class="card mt-3">
          <h5 class="card-header">Удаление вакансии</h5>
          <div class="card-body">
            <form action="{% url 'scraping:delete' object.pk %}" method="post">
              {% csrf_token %}
              <p>{{ object }}</p>
              <input type="submit" class="btn btn-primary" value="Удалить">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

scraping/templates/scraping/detail.html
{% extends 'base.html' %}

{% block title %}Детализация :: {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div>
        <div class="card mt-3">
          <h5 class="card-header">
            <a href="{{ object.url }}" class="list-group-item link-primary">{{ object.title }}</a>
          </h5>
          <div class="card-body">
            <p class="card-text">{{ object.city }} | {{ object.language }}</p>
            <p class="card-text h5">{{ object.company }}</p>
            <p class="card-text">{{ object.description }}</p>
            <p class="card-text">Добавлено: {{ object.timestamp }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

scraping/templates/scraping/index.html
{% extends 'base.html' %}

{% block title %}Главная :: {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-12 mt-5 mb-5">
        <h1>Сервис по сбору и рассылке вакансий</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 mb-5">
        <p>Заполните форму, одно или все поля</p>
        <form class="col-md-8" method="get" action="{% url 'scraping:list' %}">
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Найти</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

scraping/templates/scraping/list.html
{% extends 'base.html' %}

{% block title %}Список вакансий :: {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <h1 class="mt-3 mb-3">Список вакансий</h1>
      <ul>
        {% for vacancy in vacancies %}
        <div class="card mt-3">
          <h5 class="card-header">
            <a href="{{ vacancy.url }}" class="list-group-item link-primary">{{ vacancy.title }}</a>
          </h5>
          <div class="card-body">
            <p class="card-text">{{ vacancy.city }} | {{ vacancy.language }}</p>
            <p class="card-text h5">{{ vacancy.company }}</p>
            <p class="card-text">{{ vacancy.description }}</p>
            <p class="card-text">Добавлено: {{ vacancy.timestamp }}</p>
          </div>
        </div>
        {% empty %}
        <p>Ничего не найдено.</p>
        {% endfor %}
      </ul>
    </div>

    {% if vacancies %}
    <div class="row">
      <div class="col">
        <nav>
          <ul class="pagination justify-content-center">
            {% if vacancies.has_previous %}
            <li class="page-item">
              <a class="page-link"
                 href="?city={{ city }}&language={{ language }}&page=1"
                 title="В начало">&laquo;&laquo;</a>
            </li>
            <li class="page-item">
              <a class="page-link"
                 href="?city={{ city }}&language={{ language }}&page={{ vacancies.previous_page_number }}"
                 aria-label="Previous"
                 title="Предыдущая">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <span class="page-link"><span aria-hidden="true">&laquo;</span></span>
            </li>
            {% endif %}

            {% for page in vacancies.paginator.page_range %}
            {% if vacancies.number == page %}
            <li class="page-item active" aria-current="page">
              <span class="page-link">{{ page }}</span>
            </li>
            {% elif page > vacancies.number|add:-3 and page < vacancies.number|add:3 %}
            <li class="page-item">
              <a class="page-link" href="?city={{ city }}&language={{ language }}&page={{ page }}">{{ page }}</a>
            </li>
            {% endif %}
            {% endfor %}

            {% if vacancies.has_next %}
            <li class="page-item">
              <a class="page-link"
                 href="?city={{ city }}&language={{ language }}&page={{ vacancies.next_page_number }}"
                 aria-label="Next"
                 title="Следующая">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link"
                 href="?city={{ city }}&language={{ language }}&page={{ vacancies.paginator.num_pages }}"
                 title="В конец">&raquo;&raquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <span class="page-link"><span aria-hidden="true">&raquo;</span></span>
            </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
    {% endif %}

    <div class="row">
      <form class="col-md-4 mt-5 mb-5" method="get" action="{% url 'scraping:list' %}">
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Найти</button>
      </form>
    </div>
  </div>
{% endblock %}