accounts/urls.py
from django.urls import path

from accounts.views import login_view, logout_view, register_view, update_view, delete_view, contact_view

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('update/', update_view, name='update'),
    path('delete/', delete_view, name='delete'),
    path('contact/', contact_view, name='contact'),
]

scraping_service/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scraping.urls', namespace='scraping')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models

from scraping.models import City, Language


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Необходимо указать email-адрес.')

        user = self.model(
            email=self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        if not email:
            raise ValueError('Необходимо указать email-адрес.')

        user = self.create_user(email, password=password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True, verbose_name='Email')
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Город')
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, blank=True, null=True,
                                 verbose_name='Язык программирования')
    send_email = models.BooleanField(default=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.hashers import check_password

from scraping.models import City, Language

User = get_user_model()


class UserLoginForm(forms.Form):
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email').strip()
        password = self.cleaned_data.get('password').strip()

        if email and password:
            user_data = User.objects.filter(email=email)
            if not user_data.exists():
                raise forms.ValidationError('Такого пользователя нет')
            if not check_password(password, user_data[0].password):
                raise forms.ValidationError('Неверный пароль')
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError('Данный пользователь не активен')
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegistrationForm(forms.ModelForm):
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['email']

    def clean_password2(self):
        data = self.cleaned_data
        if data['password'] != data['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        return data['password2']


class UserUpdateForm(forms.Form):
    city = forms.ModelChoiceField(queryset=City.objects.all(), to_field_name='slug', required=True, label='Город',
                                  widget=forms.Select(attrs={'class': 'form-control'}))
    language = forms.ModelChoiceField(queryset=Language.objects.all(), to_field_name='slug', required=True,
                                      label='Язык программирования',
                                      widget=forms.Select(attrs={'class': 'form-control'}))
    send_email = forms.BooleanField(label='Получать рассылку?', required=False,
                                    widget=forms.CheckboxInput())

    class Meta:
        model = User
        fields = ['city', 'language', 'send_email']


class ContactForm(forms.Form):
    city = forms.CharField(required=True, label='Город', widget=forms.TextInput(attrs={'class': 'form-control'}))
    language = forms.CharField(required=True, label='Язык программирования',
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(required=True, label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))

accounts/views.py
import datetime

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages

from accounts.forms import UserLoginForm, UserRegistrationForm, UserUpdateForm, ContactForm
from scraping.models import Error

User = get_user_model()


def login_view(request):
    form = UserLoginForm(request.POST or None)

    if form.is_valid():
        data = form.cleaned_data
        email = data.get('email')
        password = data.get('password')
        user = authenticate(request, email=email, password=password)
        login(request, user)
        messages.success(request, 'Вы вошли в систему')
        return redirect('scraping:home')
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('scraping:home')


def register_view(request):
    form = UserRegistrationForm(request.POST or None)
    if form.is_valid():
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data['password'])
        new_user.save()
        messages.success(request, 'Вы успешно зарегистрировались на сайте')
        return render(request, 'accounts/register_done.html', {'new_user': new_user})
    return render(request, 'accounts/register.html', {'form': form})


def update_view(request):
    contact_form = ContactForm()
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'POST':
            form = UserUpdateForm(request.POST or None)
            if form.is_valid():
                data = form.cleaned_data
                user.city = data['city']
                user.language = data['language']
                user.send_email = data['send_email']
                user.save()
                messages.success(request, 'Данные сохранены')
                return redirect('accounts:update')

        form = UserUpdateForm(initial={'city': user.city, 'language': user.language, 'send_email': user.send_email})
        return render(request, 'accounts/update.html', {'form': form, 'contact_form': contact_form})
    else:
        return redirect('accounts:login')


def delete_view(request):
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'POST':
            user_data = User.objects.get(pk=user.pk)
            user_data.delete()
            messages.error(request, 'Пользователь удален')
    return redirect('scraping:home')


def contact_view(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST or None)
        if contact_form.is_valid():
            data = contact_form.cleaned_data
            city = data.get('city')
            language = data.get('language')
            email = data.get('email')
            error_data = Error.objects.filter(timestamp=datetime.date.today())
            if error_data.exists():
                err = error_data.first()
                data = err.data.get('user_data', [])
                data.append({'city': city, 'language': language, 'email': email})
                err.data['user_data'] = data
                err.save()
            else:
                data = [{'city': city, 'language': language, 'email': email}]
                Error(data=f"user_data: {data}").save()
            messages.success(request, 'Данные отправлены на рассмотрение.')
            return redirect('accounts:update')
        else:
            return redirect('accounts:update')
    else:
        return redirect('accounts:login')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Вход :: {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 mb-5">
        <h4>Вход на сайт</h4>
        <form class="col-md-8" method="post" action="{% url 'accounts:login' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Войти</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}Регистрация :: {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 mb-5">
        <h4>Регистрация нового пользователя</h4>
        <form class="col-md-8" method="post" action="{% url 'accounts:register' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Зарегистривовать</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/register_done.html
{% extends 'base.html' %}

{% block title %}Регистрация :: {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 mb-5">
        <h4>Приветствуем нового пользователя, {{ new_user }}</h4>
        <p>Вы успешно зарегистривовались в системе, можете <a href="{% url 'accounts:login' %}">войти</a></p>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block title %}Обновления данных :: {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 mb-5">
        <h4>Обновление данных пользователя</h4>
        <form class="col-md-8" method="post" action="{% url 'accounts:update' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
        <form class="col-md-8" method="post" action="{% url 'accounts:delete' %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger mt-2">Удалить</button>
        </form>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 mb-5">
        <p>Если вы не нашли нужный набор "город-язык программирования", заполните форму ниже. После добавления данных
          вы получите письмо на указанный email.</p>
        <p>
          <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapse"
                  aria-expanded="false" aria-controls="collapse">
            Показать / Скрыть форму
          </button>
        </p>
        <div class="collapse" id="collapse">
          <div class="card card-body">
            <form class="col-md-8" method="post" action="{% url 'accounts:contact' %}">
              {% csrf_token %}
              {{ contact_form.as_p }}
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}