accounts/urls.py
from django.urls import path

from accounts.views import login_view, logout_view, register_view, update_view, delete_view, contact_view

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('update/', update_view, name='update'),
    path('delete/', delete_view, name='delete'),
    path('contact/', contact_view, name='contact'),
]

scraping/urls.py
from django.urls import path

from scraping.views import home_view, list_view, detail_view, DetailPageView, ListPageView, CreatePageView, \
    UpdatePageView, DeletePageView

app_name = 'scraping'

urlpatterns = [
    # path('detail/<int:pk>/', detail_view, name='detail'),
    # path('list/', list_view, name='list'),
    path('detail/<int:pk>/', DetailPageView.as_view(), name='detail'),
    path('create/', CreatePageView.as_view(), name='create'),
    path('update/<int:pk>/', UpdatePageView.as_view(), name='update'),
    path('delete/<int:pk>/', DeletePageView.as_view(), name='delete'),
    path('list/', ListPageView.as_view(), name='list'),
    path('', home_view, name='home'),
]

scraping_service/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scraping.urls', namespace='scraping')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

templates/base.html
<!doctype html>
{% load static %}
{% url 'scraping:home' as home_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:register' as register_url %}
{% url 'accounts:update' as update_url %}
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}Сервис по сбору данных</title>
  <link rel="icon" href="{% static 'favicon.ico' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand brand-logo" href="{{ home_url }}">Job Search</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link {% if request.path == home_url %} active {% endif %}" aria-current="page"
                 href="{{ home_url }}">Главная</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active">{{ user }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Выйти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == update_url %} active {% endif %}"
                 href="{{ update_url }}">Обновить данные</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == login_url %} active {% endif %}"
                 href="{{ login_url }}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == register_url %} active {% endif %}"
                 href="{{ register_url }}">Регистрация</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-12 mt-2">
        {% if messages %}
          {% for message in messages %}
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% else %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endif %}
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>

  {% block content %}{% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
          crossorigin="anonymous"></script>
</body>
</html>